name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip openjdk-11-jdk unzip
          pip install buildozer cython

      - name: Install Android SDK and Build-Tools
        env:
          ANDROID_HOME: $HOME/.buildozer/android/platform/android-sdk
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          
          # Download and extract Android SDK Command Line Tools
          curl -o android-sdk.zip https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip
          unzip -q android-sdk.zip -d $ANDROID_HOME/cmdline-tools/temp

          # Move the extracted files properly
          mv $ANDROID_HOME/cmdline-tools/temp/cmdline-tools/* $ANDROID_HOME/cmdline-tools/
          rm -rf $ANDROID_HOME/cmdline-tools/temp

          # Accept all licenses
          yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses

          # Install the required build tools and platform tools
          $ANDROID_HOME/cmdline-tools/bin/sdkmanager "build-tools;35.0.0" "platform-tools"

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: bin/*.apk




